### DISCUSSION TITLE
My home assistant example. Hyundai Kona EV 2019

### DISCUSSION THREAD

**Discussion by chris58008** [meatpiHQ/wican-fw#86] [Show and tell]
Short example of what I have done with the wican and home assistant now :)
This works with FW [wican-fw_v292_hv300.zip](https://github.com/meatpiHQ/wican-fw/files/14126390/wican-fw_v292_hv300.zip)
![image](https://github.com/meatpiHQ/wican-fw/assets/85893534/06ab52b9-2515-4a8e-90a2-ce47ff56ddee)

```
sensor:    
#WiCAN

  - name: "WiCAN Kona Status"                                                                             
    state_topic: "wican/Your_Device_Here/can/rx" 
    value_template: '{{ value_json.status }}'
                                                                                 
  - name: "WiCAN Kona SOC BMS"                                                                             
    state_topic: "wican/Your_Device_Here/can/rx" 
    value_template: '{{ value_json.SOC_BMS|float(0) }}'
    unit_of_measurement: "%"

  - name: "WiCAN Kona Voltage BMS"                                                                             
    state_topic: "wican/Your_Device_Here/can/rx" 
    value_template: '{{ value_json.Batt_Volts|float(0) }}'
    unit_of_measurement: "V"           

  - name: "WiCAN Kona Voltage BMS Max_Cell_V"                                                                             
    state_topic: "wican/Your_Device_Here/can/rx" 
    value_template: '{{ value_json.Max_Cell_V|float(0) }}'
    unit_of_measurement: "V"    

  - name: "WiCAN Kona Voltage BMS Max_Cell_V_No"                                                                             
    state_topic: "wican/Your_Device_Here/can/rx" 
    value_template: '{{ value_json.Max_Cell_V_No|float(0)|round(0) }}'

  - name: "WiCAN Kona Voltage BMS Min_Cell_V"                                                                             
    state_topic: "wican/Your_Device_Here/can/rx" 
    value_template: '{{ value_json.Min_Cell_V|float(0) }}'
    unit_of_measurement: "V"    

  - name: "WiCAN Kona Voltage BMS Min_Cell_V_No"                                                                             
    state_topic: "wican/Your_Device_Here/can/rx" 
    value_template: '{{ value_json.Min_Cell_V_No|float(0)|round(0) }}'

  - name: "WiCAN Kona Battery Temp 1"                                                                             
    state_topic: "wican/Your_Device_Here/can/rx" 
    value_template: '{{ value_json.Batt_Temp1|float(0)|round(0) }}'
    unit_of_measurement: "°C"    

  - name: "WiCAN Kona Battery Temp 2"                                                                             
    state_topic: "wican/Your_Device_Here/can/rx" 
    value_template: '{{ value_json.Batt_Temp2|float(0)|round(0) }}'
    unit_of_measurement: "°C"    

  - name: "WiCAN Kona Battery Temp 3"                                                                             
    state_topic: "wican/Your_Device_Here/can/rx" 
    value_template: '{{ value_json.Batt_Temp3|float(0)|round(0) }}'
    unit_of_measurement: "°C"    

  - name: "WiCAN Kona Battery Temp 4"                                                                             
    state_topic: "wican/Your_Device_Here/can/rx" 
    value_template: '{{ value_json.Batt_Temp4|float(0)|round(0) }}'
    unit_of_measurement: "°C"    

  - name: "WiCAN Kona Battery Temp Inlet"                                                                             
    state_topic: "wican/Your_Device_Here/can/rx" 
    value_template: '{{ value_json.Batt_InletT|float(0)|round(0) }}'
    unit_of_measurement: "°C"

```
![image](https://github.com/meatpiHQ/wican-fw/assets/85893534/c671b562-8843-46a4-a90b-866e42cb0673)

Updater automation for home assistant
```

alias: KONA OBD UPDATER
description: ""
trigger:

platform: time_pattern
seconds: /1
enabled: true
condition: []
action:
service: mqtt.publish
data:
qos: "0"
topic: wican/Your_Device_Here/can/tx
payload: >-
{"bus":"0","type":"tx","ts":4406,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[3,34,1,1,170,170,170,170]}]}
enabled: true
delay:
hours: 0
minutes: 0
seconds: 0
milliseconds: 200
enabled: true
service: mqtt.publish
data:
qos: "0"
topic: wican/Your_Device_Here/can/tx
payload: >-
{"bus":"0","type":"tx","ts":4428,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[48,0,10,170,170,170,170,170]}]}
enabled: true
mode: single
```

Example of data captured while carscanner is running and displaying BMS SOC
```
{"bus":"0","type":"tx","ts":4406,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[3,34,1,1,170,170,170,170]}]}
{"bus":"0","type":"rx","ts":4419,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[16,62,98,1,1,255,247,231]}]}
{"bus":"0","type":"tx","ts":4428,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[48,0,10,170,170,170,170,170]}]}
{"bus":"0","type":"rx","ts":4434,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[33,255,143,16,118,0,238,3]}]}
{"bus":"0","type":"rx","ts":4448,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[34,255,179,15,33,4,3,2]}]}
{"bus":"0","type":"rx","ts":4464,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[35,2,3,3,0,0,3,197]}]}
{"bus":"0","type":"rx","ts":4478,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[36,40,197,39,0,0,146,0]}]}
{"bus":"0","type":"rx","ts":4494,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[37,3,16,187,0,3,12,170]}]}
{"bus":"0","type":"rx","ts":4508,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[38,0,1,29,80,0,1,20]}]}
{"bus":"0","type":"rx","ts":4526,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[39,39,1,139,139,128,9,1]}]}
{"bus":"0","type":"rx","ts":5198,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[40,131,0,0,0,0,11,184]}]}
```

**Comment by HaareistNase** [comment]
Looks amazing.
But could you pls explain where you found the "working" PIDs you used, and how you translate them from the cryptic format they are published to the format you used?

I recived my wican two days ago, and until now I tryed to get data by publish things like 

{ "bus": "0", "type": "tx", "frame": [{ "id": 2015, "dlc": 8, "rtr": false, "extd": false, "data": [3, 22, 1, 5, 170, 170, 170, 170] }] };

via mytt to my nero ev

Thank you.

**Reply by chris58008** [reply]
I used car scanner to capture, and https://docs.google.com/spreadsheets/d/1-9jZafV9eZeBUnPQo7qQHbX2-_4qZfWfRVpidoF1owA/edit#gid=0


`alias: KONA OBD UPDATER
description: ""
trigger:
  - platform: time_pattern
    seconds: /1
    enabled: true
condition: []
action:
  - service: mqtt.publish
    data:
      qos: "0"
      topic: wican/xxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":4406,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[3,34,1,1,170,170,170,170]}]}
    enabled: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 200
    enabled: true
  - service: mqtt.publish
    data:
      qos: "0"
      topic: wican/xxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":4428,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[48,0,10,170,170,170,170,170]}]}
    enabled: true
mode: single`

**Comment by HaareistNase** [comment]
thx for your very very quick response.
Thats EXACTLY what I mean.

Just imagine, that I have no clue what you are talking about.
I just want to see the bms-soc on my kia

I found in your google sheet something about


BC
e [7:8]
94
SOC BMS



Maybe for you its easy to read. But I have not the slightest clue, what I do with this info.

**Reply by chris58008** [reply]
BC is the hex value of the SOC
BC hex = 188 (base10)
This value is divided by 2 to get the 94 % SOC
![image](https://github.com/meatpiHQ/wican-fw/assets/85893534/e8637e45-52ec-4220-a87b-d4fe55a2ca4c)

**Comment by HaareistNase** [comment]
Cool. Thank you.
But the rest is still poking in the mist for me.

Maybe you are so kind to explain what I have to send to the wican to get this value.

**Reply by chris58008** [reply]
I send this via mqqt in home assistant.
```

alias: KONA OBD UPDATER
description: ""
trigger:

platform: time_pattern
seconds: /1
enabled: true
condition: []
action:
service: mqtt.publish
data:
qos: "0"
topic: wican/xxx/can/tx
payload: >-
{"bus":"0","type":"tx","ts":4406,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[3,34,1,1,170,170,170,170]}]}
enabled: true
delay:
hours: 0
minutes: 0
seconds: 0
milliseconds: 200
enabled: true
service: mqtt.publish
data:
qos: "0"
topic: wican/xxx/can/tx
payload: >-
{"bus":"0","type":"tx","ts":4428,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[48,0,10,170,170,170,170,170]}]}
enabled: true
mode: single
```

**Comment by HaareistNase** [comment]
Thats the same you postet ago. I tryd this tonight while charging the car, but get no "changing" results, where I can guess what value is the right one.
Thank you again. I will try again after work. I appriciate your support.

**Reply by chris58008** [reply]
Is "mqtt elm327 log" enable or disabled?

**Reply by chris58008** [reply]
Did you look at this guide? https://github.com/meatpiHQ/wican-fw/wiki/EV-Battery-SoC-in-Home-Assistant-%E2%80%90-Example

**Comment by HaareistNase** [comment]
it is disabled.
BUT. I just checked what the car answered 2h ago, as I start my way to work.
The last reading differs very from the readings tonigt.

It is

[16, 62, 98, 1, 1, 255, 247, 231]

And I startet with a SOC auf 74% (in the odometer) after charging.
And again I am lost. There is no value of 148 (or in the range of it). 




```
alias: MQTT E-Niro Update
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.niro_status_mqtt
    to: online
condition: []
action:
  - repeat:
      count: 240
      sequence:
        - condition: state
          entity_id: sensor.niro_status_mqtt
          state: online
        - service: mqtt.publish
          data:
            qos: 0
            retain: false
            payload: >-
              {"bus":"0","type":"tx","ts":4406,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[3,34,1,1,170,170,170,170]}]}
            topic: wican/myid/can/tx
        - delay:
            hours: 0
            minutes: 1
            seconds: 0
            milliseconds: 200
        - service: mqtt.publish
          data:
            qos: 0
            retain: false
            payload: >-
              {"bus":"0","type":"tx","ts":4428,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[48,0,10,170,170,170,170,170]}]}
            topic: wican/myid/can/tx
        - delay:
            hours: 0
            minutes: 1
            seconds: 0
            milliseconds: 0
mode: single
```
