### ISSUE TITLE
Retained MQTT Data

### ISSUE THREAD

**Issue by HaareistNase** [meatpiHQ/wican-fw#134]
Dear Sirs,
Is there a posibility to make the MQTT Data Wican sends „retained“.

I use Home Assistant to Display the MQTT Data from Wican, and every time I restart Home Assistant while wican is not online (because the car is not home or wican is in sleep mode) I get an unknown Sensor Status in Home Assistant.

**Comment by HaareistNase** [comment]
Ah. I Export the values to MQTT again with retained flag, and than they do stay. No Need to change. Sorry for bother:-)

**Comment by justynbell** [comment]
@HaareistNase could you go into details about what you mean?  Is this a setting in the HA MQTT sensor configuration?  Is this a configuration in the WiCAN settings somewhere?

**Comment by HaareistNase** [comment]
>Is this a setting in the HA MQTT sensor configuration? Is this a configuration in the WiCAN settings somewhere?

Hey. Im not a programmer or homeassistant-nerd. So maybe Im wrong. Its just my experience.

So you can't change settings about this in wican. There is no option. So all you can do is handle it in homeassistant.


I create a mqtt-sensor to "fetch" the SOC from my e-Niro in configuration.yaml

```
mqtt:
  sensor:
    - name: "E-UP SOC MQTT"
      unique_id: "sensor.e_up_soc_mqtt"
      state_topic: "wican/5432048fef81/can/rx"
      value_template: "{{ value_json.BMS_SOC|float(0)| round(1) }}"
      icon: mdi:battery
      unit_of_measurement: "%"
```

but I can't make the values from this sensor "permanent".
Every time I reset homeassistant (and I reset it quite regularly because of the many updates this software get, and the work I put into it) it will "forget" the last value and I get a "unknown" in my display. I do not know how to fix this with a setting or parameter.

So I do "Export" this value again (I know, its double-work for homeassistant, but I don't care".

This is the automatisation for export

```
service: mqtt.publish
data:
  qos: 0
  retain: true
  topic: export/soc
  payload_template: "{{ states('sensor.e_up_soc_mqtt') }}"
```

Here I can set "retain: true" so homeassistant "saves" the value in his database, and it will be preserved over a system-restart and I do not get a "unknown" in my display.


Hope this helps. And maybe you know a better way :-)
